/**
 * Root site metadata (B2/U11) — extracted from `app/layout.tsx` so unit
 * tests can assert the Open Graph / Twitter contract without loading
 * next/font or the CSS pipeline.
 *
 * Production origin: `https://landing.ene-muebles.cl` — the value the
 * operator set in `infrastructure/.env` (`NEXT_PUBLIC_SITE_URL`,
 * `DOMAIN`) and that docker-compose REQUIRES at deploy time
 * (`${NEXT_PUBLIC_SITE_URL:?...}`), so the spec's "MUST NOT invent a
 * host" is enforced at the deploy boundary. `metadataBase` stays
 * env-overridable: local dev falls back to the local URL, production
 * always supplies the real origin.
 */
import { APP_VERSION } from "./version";

const SITE_URL =
  process.env.NEXT_PUBLIC_SITE_URL?.replace(/\/+$/, "") ?? "http://localhost:4780";

/** OG image generated by `app/opengraph-image.tsx` (file convention). */
const OG_IMAGE_PATH = "/opengraph-image";

const OG_TITLE = "ENE-MUEBLES · Mobiliario escolar y de oficina";
const OG_DESCRIPTION =
  "Mobiliario institucional para aulas, oficinas e instituciones en Chile. Catálogo 2026, despacho desde la Región de Valparaíso hasta la Región de Los Lagos y cotización en 24 h hábiles.";

export const siteMetadata = {
  metadataBase: new URL(SITE_URL),
  title: {
    default: OG_TITLE,
    template: "%s · ENE-MUEBLES",
  },
  description:
    "Mobiliario escolar y de oficina certificado para instituciones en Chile. Catálogo, despacho desde la Región de Valparaíso hasta la Región de Los Lagos y cotización en 24 h.",
  openGraph: {
    type: "website",
    locale: "es_CL",
    siteName: "ENE-MUEBLES",
    title: OG_TITLE,
    description: OG_DESCRIPTION,
    images: [
      {
        url: OG_IMAGE_PATH,
        width: 1200,
        height: 630,
        alt: "ENE Muebles — Mobiliario institucional · Catálogo · Regiones desde Valparaíso hasta Los Lagos",
      },
    ],
  },
  twitter: {
    card: "summary_large_image",
    title: OG_TITLE,
    description: OG_DESCRIPTION,
    images: [OG_IMAGE_PATH],
  },
  robots: {
    index: true,
    follow: true,
  },
  other: {
    version: APP_VERSION,
  },
} as const;
